Repository Breaking-Dope/breaking-android, pull requests merged in 2022-09, with the labels that each got.

#102 fix : post detail problems
  Breaking/app/src/main/java/com/dope/breaking/board/PostDetailActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/fragment/NaviHomeFragment.kt
  Breaking/app/src/main/java/com/dope/breaking/fragment/user_tab/BookmarkedTabFragment.kt
  Breaking/app/src/main/java/com/dope/breaking/fragment/user_tab/PostTabFragment.kt
  Breaking/app/src/main/java/com/dope/breaking/fragment/user_tab/PurchasedTabFragment.kt
  Breaking/app/src/main/res/drawable/bg_indicator_active.xml
  Breaking/app/src/main/res/layout/activity_post_detail.xml
  Breaking/app/src/main/res/layout/skeleton_item_post_detail.xml
Labels: :ambulance: Hot-Fix, ✒Style

#104 hotfix: add handling for empty list of search result
  Breaking/app/src/main/java/com/dope/breaking/FeedSearchActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/adapter/FeedAdapter.kt
  Breaking/app/src/main/res/layout/activity_feed_search.xml
  Breaking/app/src/main/res/layout/fragment_navi_home.xml
  Breaking/app/src/main/res/layout/item_post_list.xml
  Breaking/app/src/main/res/layout/item_user_search.xml
  Breaking/app/src/main/res/layout/skeleton_item_post_list.xml
Labels: :bug: Bug, :ambulance: Hot-Fix, :recycle: Refactoring

#107 feat: Implement post comment, nested comment
  Breaking/app/src/main/AndroidManifest.xml
  Breaking/app/src/main/java/com/dope/breaking/board/PostCommentAdapter.kt
  Breaking/app/src/main/java/com/dope/breaking/board/PostDetailActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/board/PostNestedCommentAdapter.kt
  Breaking/app/src/main/java/com/dope/breaking/model/request/RequestComment.kt
  Breaking/app/src/main/java/com/dope/breaking/model/response/ResponseComment.kt
  Breaking/app/src/main/java/com/dope/breaking/model/response/ResponseCommentUser.kt
  Breaking/app/src/main/java/com/dope/breaking/post/PostManager.kt
  Breaking/app/src/main/java/com/dope/breaking/retrofit/RetrofitService.kt
  Breaking/app/src/main/java/com/dope/breaking/util/ValueUtil.kt
  Breaking/app/src/main/res/layout/activity_post_detail.xml
  Breaking/app/src/main/res/layout/item_comment_list.xml
  Breaking/app/src/main/res/layout/item_nested_comment_list.xml
  Breaking/app/src/main/res/values/strings.xml
Labels: :exclamation: Important, :sparkles: Function

#108 feat: implement financial function (deposit, withdraw, transaction list)
  Breaking/app/src/main/AndroidManifest.xml
  Breaking/app/src/main/java/com/dope/breaking/FinanceActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/SettingActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/adapter/FinanceViewPagerAdapter.kt
  Breaking/app/src/main/java/com/dope/breaking/adapter/TransactionAdapter.kt
  Breaking/app/src/main/java/com/dope/breaking/finance/FinanceManager.kt
  Breaking/app/src/main/java/com/dope/breaking/fragment/finance_tab/ChargeTabFragment.kt
  Breaking/app/src/main/java/com/dope/breaking/fragment/finance_tab/TransactionListTabFragment.kt
  Breaking/app/src/main/java/com/dope/breaking/fragment/finance_tab/WithdrawTabFragment.kt
  Breaking/app/src/main/java/com/dope/breaking/model/request/RequestAmount.kt
  Breaking/app/src/main/java/com/dope/breaking/model/response/ResponseExistLogin.kt
  Breaking/app/src/main/java/com/dope/breaking/model/response/ResponseTransaction.kt
  Breaking/app/src/main/java/com/dope/breaking/retrofit/RetrofitService.kt
  Breaking/app/src/main/java/com/dope/breaking/util/ValueUtil.kt
  Breaking/app/src/main/res/drawable/border_white_background.xml
  Breaking/app/src/main/res/drawable/finance_other_background.xml
  Breaking/app/src/main/res/drawable/finance_self_background.xml
  Breaking/app/src/main/res/drawable/text_click_background.xml
  Breaking/app/src/main/res/layout/activity_finance.xml
  Breaking/app/src/main/res/layout/activity_setting.xml
  Breaking/app/src/main/res/layout/fragment_finance_charge.xml
  Breaking/app/src/main/res/layout/fragment_finance_transaction.xml
  Breaking/app/src/main/res/layout/fragment_finance_withdraw.xml
  Breaking/app/src/main/res/layout/item_transaction_other.xml
  Breaking/app/src/main/res/layout/item_transaction_self.xml
  Breaking/app/src/main/res/values/strings.xml
Labels: :sparkles: Function

#111 feat: implement refresh main feed
  Breaking/app/build.gradle
  Breaking/app/src/main/java/com/dope/breaking/fragment/NaviHomeFragment.kt
  Breaking/app/src/main/java/com/dope/breaking/util/DialogUtil.kt
  Breaking/app/src/main/res/layout/fragment_navi_home.xml
Labels: :sparkles: Function

#114 hotfix: add condition for renew data by scroll event
  Breaking/app/src/main/java/com/dope/breaking/FinanceActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/UserPageActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/fragment/NaviUserFragment.kt
  Breaking/app/src/main/java/com/dope/breaking/fragment/user_tab/BookmarkedTabFragment.kt
  Breaking/app/src/main/java/com/dope/breaking/fragment/user_tab/PostTabFragment.kt
  Breaking/app/src/main/java/com/dope/breaking/fragment/user_tab/PurchasedTabFragment.kt
  Breaking/app/src/main/java/com/dope/breaking/util/ValueUtil.kt
  Breaking/app/src/main/res/layout/fragment_bookmarked_tab.xml
  Breaking/app/src/main/res/layout/fragment_post_tab.xml
  Breaking/app/src/main/res/layout/fragment_purchased_tab.xml
Labels: :bug: Bug, :ambulance: Hot-Fix

#115 feat: Implement delete, correction about post detail & add view about post detail
  Breaking/app/src/main/AndroidManifest.xml
  Breaking/app/src/main/java/com/dope/breaking/EditPostActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/board/PostActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/board/PostDetailActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/fragment/NaviHomeFragment.kt
  Breaking/app/src/main/java/com/dope/breaking/model/PostLocation.kt
  Breaking/app/src/main/java/com/dope/breaking/model/request/RequestPostDataModify.kt
  Breaking/app/src/main/java/com/dope/breaking/model/response/ResponsePostDetail.kt
  Breaking/app/src/main/java/com/dope/breaking/post/PostManager.kt
  Breaking/app/src/main/java/com/dope/breaking/retrofit/RetrofitService.kt
  Breaking/app/src/main/res/drawable/ic_baseline_cancel_24.xml
  Breaking/app/src/main/res/drawable/ic_post_activation.xml
  Breaking/app/src/main/res/layout/activity_post.xml
  Breaking/app/src/main/res/layout/activity_post_detail.xml
  Breaking/app/src/main/res/layout/custom_post_detail_content_popup.xml
  Breaking/app/src/main/res/layout/item_comment_list.xml
  Breaking/app/src/main/res/layout/item_nested_comment_list.xml
  Breaking/app/src/main/res/values/strings.xml
Labels: :sparkles: Function, ✒Style

#116 feat: Implement video processing about posting
  Breaking/app/build.gradle
  Breaking/app/src/main/java/com/dope/breaking/board/ImageSliderAdapter.kt
  Breaking/app/src/main/java/com/dope/breaking/board/MultiImageAdapter.kt
  Breaking/app/src/main/java/com/dope/breaking/board/PostActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/board/PostDetailActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/post/PostManager.kt
  Breaking/app/src/main/java/com/dope/breaking/retrofit/RetrofitManager.kt
  Breaking/app/src/main/java/com/dope/breaking/util/Utils.kt
  Breaking/app/src/main/res/layout/item_slider.xml
  Breaking/settings.gradle
Labels: :exclamation: Important, :sparkles: Function

#122 feat: Implement post detail like component
  Breaking/app/src/main/AndroidManifest.xml
  Breaking/app/src/main/java/com/dope/breaking/board/PostDetailActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/board/PostLikeActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/post/PostManager.kt
  Breaking/app/src/main/java/com/dope/breaking/retrofit/RetrofitService.kt
  Breaking/app/src/main/java/com/dope/breaking/util/ValueUtil.kt
  Breaking/app/src/main/res/drawable/ic_post_comment.xml
  Breaking/app/src/main/res/drawable/ic_post_like_after.xml
  Breaking/app/src/main/res/layout/activity_post_detail.xml
Labels: :sparkles: Function

#123 feat: Implement post detail purchase component
  Breaking/app/src/main/AndroidManifest.xml
  Breaking/app/src/main/java/com/dope/breaking/adapter/FeedAdapter.kt
  Breaking/app/src/main/java/com/dope/breaking/board/PostCommentAdapter.kt
  Breaking/app/src/main/java/com/dope/breaking/board/PostDetailActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/board/PostLikeListActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/board/PostNestedCommentAdapter.kt
  Breaking/app/src/main/java/com/dope/breaking/board/PostPurchaseListActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/model/response/ResponsePostDetail.kt
  Breaking/app/src/main/java/com/dope/breaking/post/PostManager.kt
  Breaking/app/src/main/java/com/dope/breaking/retrofit/RetrofitService.kt
  Breaking/app/src/main/java/com/dope/breaking/util/ValueUtil.kt
  Breaking/app/src/main/res/drawable/btn_post_detail_purchase.xml
  Breaking/app/src/main/res/drawable/ic_post_activate.xml
  Breaking/app/src/main/res/drawable/ic_post_deactivate.xml
  Breaking/app/src/main/res/layout/activity_post_detail.xml
  Breaking/app/src/main/res/layout/custom_post_detail_content_popup.xml
  Breaking/app/src/main/res/layout/item_post_list.xml
  Breaking/app/src/main/res/values/colors.xml
  Breaking/app/src/main/res/values/strings.xml
Labels: :sparkles: Function

#124 feat: Implement post detail bookmark, hide
  Breaking/app/src/main/java/com/dope/breaking/adapter/FeedAdapter.kt
  Breaking/app/src/main/java/com/dope/breaking/board/PostDetailActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/model/response/ResponseMainFeed.kt
  Breaking/app/src/main/java/com/dope/breaking/model/response/ResponsePostDetail.kt
  Breaking/app/src/main/java/com/dope/breaking/post/PostManager.kt
  Breaking/app/src/main/java/com/dope/breaking/retrofit/RetrofitService.kt
  Breaking/app/src/main/res/drawable/chip_post_hidden_background.xml
  Breaking/app/src/main/res/drawable/ic_post_hide.xml
  Breaking/app/src/main/res/drawable/ic_post_unhide.xml
  Breaking/app/src/main/res/layout/activity_post_detail.xml
  Breaking/app/src/main/res/layout/custom_post_detail_content_popup.xml
  Breaking/app/src/main/res/layout/item_post_list.xml
  Breaking/app/src/main/res/values/colors.xml
  Breaking/app/src/main/res/values/strings.xml
Labels: :sparkles: Function

#125 fix: resolved problem of video sound, memory leak
  Breaking/app/src/main/AndroidManifest.xml
  Breaking/app/src/main/java/com/dope/breaking/board/ImageSliderAdapter.kt
  Breaking/app/src/main/java/com/dope/breaking/board/PostDetailActivity.kt
Labels: :bug: Bug, :ambulance: Hot-Fix

#127 feat: Implement post detail comment like, modify, delete
  Breaking/app/src/main/java/com/dope/breaking/board/PostCommentAdapter.kt
  Breaking/app/src/main/java/com/dope/breaking/board/PostDetailActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/board/PostNestedCommentAdapter.kt
  Breaking/app/src/main/java/com/dope/breaking/model/response/ResponseComment.kt
  Breaking/app/src/main/java/com/dope/breaking/post/PostManager.kt
  Breaking/app/src/main/java/com/dope/breaking/retrofit/RetrofitService.kt
  Breaking/app/src/main/java/com/dope/breaking/util/ValueUtil.kt
  Breaking/app/src/main/res/layout/activity_post_detail.xml
  Breaking/app/src/main/res/layout/custom_comment_more_popup.xml
  Breaking/app/src/main/res/layout/item_comment_list.xml
  Breaking/app/src/main/res/layout/item_nested_comment_list.xml
Labels: :sparkles: Function

#128 refactor: fix split user tab according to current user
  Breaking/app/src/main/AndroidManifest.xml
  Breaking/app/src/main/java/com/dope/breaking/FeedSearchActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/adapter/UserViewPagerAdapter.kt
  Breaking/app/src/main/res/layout/fragment_bookmarked_tab.xml
  Breaking/app/src/main/res/layout/fragment_navi_user.xml
  Breaking/app/src/main/res/layout/fragment_post_tab.xml
  Breaking/app/src/main/res/layout/fragment_purchased_tab.xml
Labels: :recycle: Refactoring

#131 feat: distinguish login user and unlogin user
  Breaking/app/src/main/AndroidManifest.xml
  Breaking/app/src/main/java/com/dope/breaking/MainActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/SplashActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/UserPageActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/adapter/FeedAdapter.kt
  Breaking/app/src/main/java/com/dope/breaking/board/PostDetailActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/follow/Follow.kt
  Breaking/app/src/main/java/com/dope/breaking/fragment/NaviHomeFragment.kt
  Breaking/app/src/main/java/com/dope/breaking/model/response/ResponsePostWriter.kt
  Breaking/app/src/main/java/com/dope/breaking/post/PostManager.kt
  Breaking/app/src/main/res/drawable/ic_baseline_comment_24.xml
  Breaking/app/src/main/res/drawable/ic_baseline_thumb_up_alt_24.xml
  Breaking/app/src/main/res/drawable/ic_post_comment_disable.xml
  Breaking/app/src/main/res/drawable/ic_post_like_disable.xml
  Breaking/app/src/main/res/layout/activity_main.xml
  Breaking/app/src/main/res/layout/activity_post_detail.xml
  Breaking/app/src/main/res/layout/item_post_list.xml
  Breaking/app/src/main/res/values/themes.xml
Labels: :exclamation: Important, :recycle: Refactoring, :sparkles: Function

#132 feat: Implement post media download
  Breaking/app/build.gradle
  Breaking/app/src/main/AndroidManifest.xml
  Breaking/app/src/main/java/com/dope/breaking/FeedSearchActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/MainActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/board/PostDetailActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/post/PostManager.kt
  Breaking/app/src/main/java/com/dope/breaking/retrofit/RetrofitService.kt
  Breaking/app/src/main/java/com/dope/breaking/util/Utils.kt
  Breaking/app/src/main/res/drawable/bottom_icon_color.xml
  Breaking/app/src/main/res/drawable/ic_navi_menu_chart.xml
  Breaking/app/src/main/res/layout/activity_main.xml
  Breaking/app/src/main/res/menu/navi_menu.xml
  Breaking/app/src/main/res/values/dimens.xml
Labels: :sparkles: Function, ✒Style

#142 hotfix: add import line occurred by conflict merge
  Breaking/.gitignore
  Breaking/app/src/main/AndroidManifest.xml
  Breaking/app/src/main/java/com/dope/breaking/EditPostActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/EditProfileActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/FeedSearchActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/NaviBookActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/NaviPointActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/NaviProfileActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/NaviPurchaseActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/UserPageActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/board/ImageSliderAdapter.kt
  Breaking/app/src/main/java/com/dope/breaking/board/MultiImageAdapter.kt
  Breaking/app/src/main/java/com/dope/breaking/board/PostActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/board/PostCommentAdapter.kt
  Breaking/app/src/main/java/com/dope/breaking/board/PostDetailActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/board/PostLikeListActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/board/PostNestedCommentAdapter.kt
  Breaking/app/src/main/java/com/dope/breaking/board/PostPurchaseListActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/map/KakaoMapActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/map/MapListAdapter.kt
  Breaking/app/src/main/java/com/dope/breaking/post/PostManager.kt
  Breaking/app/src/main/java/com/dope/breaking/post/ValidationPost.kt
  Breaking/app/src/main/java/com/dope/breaking/retrofit/RetrofitManager.kt
  Breaking/app/src/main/java/com/dope/breaking/signup/ValidationSignUp.kt
  Breaking/app/src/main/java/com/dope/breaking/util/Utils.kt
Labels: :ambulance: Hot-Fix, :recycle: Refactoring
