Repository Breaking-Dope/breaking-android, pull requests merged in 2022-07, with the labels that each got.

#12 feat: implemented Splash, Sign-In View
  Breaking/app/build.gradle
  Breaking/app/src/main/AndroidManifest.xml
  Breaking/app/src/main/java/com/dope/breaking/SignInActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/SplashActivity.kt
  Breaking/app/src/main/res/anim/fade_in.xml
  Breaking/app/src/main/res/anim/fade_out.xml
  Breaking/app/src/main/res/drawable-v24/btn_sign_in_google.png
  Breaking/app/src/main/res/drawable-v24/btn_sign_in_kakao.png
  Breaking/app/src/main/res/drawable-v24/sign_in_logo_breaking.png
  Breaking/app/src/main/res/drawable/btn_google_logo_resize.xml
  Breaking/app/src/main/res/drawable/btn_kakao_logo_resize.xml
  Breaking/app/src/main/res/drawable/btn_sign_in_round.xml
  Breaking/app/src/main/res/layout/activity_main.xml
  Breaking/app/src/main/res/layout/activity_sign_in.xml
  Breaking/app/src/main/res/layout/activity_splash.xml
  Breaking/app/src/main/res/values/colors.xml
  Breaking/app/src/main/res/values/strings.xml
  Breaking/app/src/main/res/values/themes.xml
Labels: ✒Style

#13 style: implement Sign-up Page
  Breaking/.idea/gradle.xml
  Breaking/.idea/misc.xml
  Breaking/app/src/main/AndroidManifest.xml
  Breaking/app/src/main/java/com/dope/breaking/SignUpActivity.kt
  Breaking/app/src/main/res/drawable/ic_default_profile_image.xml
  Breaking/app/src/main/res/drawable/sign_up_button_background.xml
  Breaking/app/src/main/res/drawable/sign_up_input_background.xml
  Breaking/app/src/main/res/drawable/sign_up_user_type_selected.xml
  Breaking/app/src/main/res/drawable/sign_up_user_type_unselected.xml
  Breaking/app/src/main/res/layout/activity_sign_up.xml
  Breaking/app/src/main/res/values/colors.xml
  Breaking/app/src/main/res/values/strings.xml
Labels: ✒Style

#14 feat: implemented Kakao login function
  Breaking/app/build.gradle
  Breaking/app/src/main/AndroidManifest.xml
  Breaking/app/src/main/java/com/dope/breaking/GlobalApplication.kt
  Breaking/app/src/main/java/com/dope/breaking/SignInActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/model/KakaoLogin.kt
  Breaking/app/src/main/java/com/dope/breaking/model/RequestKakaoToken.kt
  Breaking/app/src/main/java/com/dope/breaking/retrofit/RetrofitManager.kt
  Breaking/app/src/main/java/com/dope/breaking/retrofit/RetrofitService.kt
  Breaking/settings.gradle
Labels: :sparkles: Function

#16 style: Implement addtional parts of Sign-up View
  Breaking/app/src/main/java/com/dope/breaking/SignUpActivity.kt
  Breaking/app/src/main/res/layout/activity_sign_up.xml
  Breaking/app/src/main/res/values/colors.xml
  Breaking/app/src/main/res/values/strings.xml
Labels: ✒Style

#21 feat: implement sign-up request, store and validate Jwt token
  Breaking/app/src/main/java/com/dope/breaking/SignInActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/SignUpActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/exception/MissingJwtTokenException.kt
  Breaking/app/src/main/java/com/dope/breaking/exception/ResponseErrorException.kt
  Breaking/app/src/main/java/com/dope/breaking/model/RequestSignUp.kt
  Breaking/app/src/main/java/com/dope/breaking/model/ResponseJwtUserInfo.kt
  Breaking/app/src/main/java/com/dope/breaking/model/ResponseLogin.kt
  Breaking/app/src/main/java/com/dope/breaking/oauth/GoogleLogin.kt
  Breaking/app/src/main/java/com/dope/breaking/retrofit/RetrofitService.kt
  Breaking/app/src/main/java/com/dope/breaking/signup/Register.kt
  Breaking/app/src/main/java/com/dope/breaking/util/JwtTokenUtil.kt
  Breaking/app/src/main/java/com/dope/breaking/util/PreferenceUtil.kt
  Breaking/app/src/test/java/com/dope/breaking/RequestSignUpTest.kt
Labels: :exclamation: Important, :sparkles: Function, :test_tube: Test

#22 feat : implement sign-up process, validate fields, final request
  Breaking/app/.idea/.gitignore
  Breaking/app/.idea/.name
  Breaking/app/.idea/compiler.xml
  Breaking/app/.idea/deploymentTargetDropDown.xml
  Breaking/app/.idea/encodings.xml
  Breaking/app/.idea/gradle.xml
  Breaking/app/.idea/misc.xml
  Breaking/app/.idea/modules.xml
  Breaking/app/.idea/vcs.xml
  Breaking/app/build.gradle
  Breaking/app/gradle/wrapper/gradle-wrapper.jar
  Breaking/app/gradle/wrapper/gradle-wrapper.properties
  Breaking/app/gradlew
  Breaking/app/gradlew.bat
  Breaking/app/src/main/AndroidManifest.xml
  Breaking/app/src/main/java/com/dope/breaking/SignInActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/SignUpActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/model/request/RequestGoogleAccessToken.kt
  Breaking/app/src/main/java/com/dope/breaking/model/request/RequestGoogleToken.kt
  Breaking/app/src/main/java/com/dope/breaking/model/request/RequestKakaoToken.kt
  Breaking/app/src/main/java/com/dope/breaking/model/request/RequestSignUp.kt
  Breaking/app/src/main/java/com/dope/breaking/model/response/ResponseGoogleAccessToken.kt
  Breaking/app/src/main/java/com/dope/breaking/model/response/ResponseJwtUserInfo.kt
  Breaking/app/src/main/java/com/dope/breaking/model/response/ResponseLogin.kt
  Breaking/app/src/main/java/com/dope/breaking/oauth/GoogleLogin.kt
  Breaking/app/src/main/java/com/dope/breaking/retrofit/RetrofitService.kt
  Breaking/app/src/main/java/com/dope/breaking/signup/Register.kt
  Breaking/app/src/main/java/com/dope/breaking/signup/Validation.kt
  Breaking/app/src/main/java/com/dope/breaking/util/JwtTokenUtil.kt
  Breaking/app/src/main/java/com/dope/breaking/util/Utils.kt
  Breaking/app/src/main/res/layout/activity_sign_up.xml
  Breaking/app/src/main/res/values/strings.xml
  Breaking/app/src/main/res/xml/provider_paths.xml
  Breaking/app/src/test/java/com/dope/breaking/RequestSignUpTest.kt
Labels: :exclamation: Important, :sparkles: Function

#29 hotfix: handling different response of google login request
  Breaking/app/.idea/.gitignore
  Breaking/app/.idea/.name
  Breaking/app/.idea/compiler.xml
  Breaking/app/.idea/deploymentTargetDropDown.xml
  Breaking/app/.idea/encodings.xml
  Breaking/app/.idea/gradle.xml
  Breaking/app/.idea/misc.xml
  Breaking/app/.idea/modules.xml
  Breaking/app/.idea/vcs.xml
  Breaking/app/gradle/wrapper/gradle-wrapper.jar
  Breaking/app/gradle/wrapper/gradle-wrapper.properties
  Breaking/app/gradlew
  Breaking/app/gradlew.bat
  Breaking/app/src/main/java/com/dope/breaking/SignInActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/SignUpActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/exception/InvalidAccessTokenException.kt
  Breaking/app/src/main/java/com/dope/breaking/model/request/RequestSignUp.kt
  Breaking/app/src/main/java/com/dope/breaking/model/response/ResponseExistLogin.kt
  Breaking/app/src/main/java/com/dope/breaking/model/response/ResponseJwtUserInfo.kt
  Breaking/app/src/main/java/com/dope/breaking/model/response/ResponseLogin.kt
  Breaking/app/src/main/java/com/dope/breaking/oauth/GoogleLogin.kt
  Breaking/app/src/main/java/com/dope/breaking/retrofit/RetrofitService.kt
  Breaking/app/src/main/java/com/dope/breaking/util/JwtTokenUtil.kt
  Breaking/app/src/main/java/com/dope/breaking/util/PreferenceUtil.kt
Labels: :bug: Bug, :ambulance: Hot-Fix, :exclamation: Important

#32 refactor : changed conflict files
  Breaking/app/.idea/.gitignore
  Breaking/app/.idea/.name
  Breaking/app/.idea/compiler.xml
  Breaking/app/.idea/deploymentTargetDropDown.xml
  Breaking/app/.idea/encodings.xml
  Breaking/app/.idea/gradle.xml
  Breaking/app/.idea/misc.xml
  Breaking/app/.idea/modules.xml
  Breaking/app/.idea/vcs.xml
  Breaking/app/gradle/wrapper/gradle-wrapper.jar
  Breaking/app/gradle/wrapper/gradle-wrapper.properties
  Breaking/app/gradlew
  Breaking/app/gradlew.bat
  Breaking/app/src/main/AndroidManifest.xml
  Breaking/app/src/main/java/com/dope/breaking/SignUpActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/SplashActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/model/response/ResponseJwtUserInfo.kt
  Breaking/app/src/main/java/com/dope/breaking/retrofit/RetrofitService.kt
Labels: :recycle: Refactoring

#36 feat: handle exception view for google login and sign-up
  Breaking/app/src/main/java/com/dope/breaking/SignInActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/SignUpActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/SplashActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/util/DialogUtil.kt
  Breaking/app/src/main/res/drawable/custom_dialog_background.xml
  Breaking/app/src/main/res/drawable/custom_dialog_multi_left_background.xml
  Breaking/app/src/main/res/drawable/custom_dialog_multi_right_background.xml
  Breaking/app/src/main/res/drawable/theme_button_background.xml
  Breaking/app/src/main/res/layout/custom_dialog_multiple_button.xml
  Breaking/app/src/main/res/layout/custom_dialog_single_button.xml
  Breaking/app/src/main/res/layout/progress_dialog_layout.xml
Labels: :sparkles: Function, :test_tube: Test, ✒Style

#38 hotfix: handling variety of response case on Kakao login
  Breaking/app/src/main/java/com/dope/breaking/SignInActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/retrofit/RetrofitService.kt
Labels: :ambulance: Hot-Fix, :exclamation: Important, :recycle: Refactoring

#39 hotfix: fixed handling signup error using jsonObject
  Breaking/app/src/main/java/com/dope/breaking/signup/Validation.kt
  Breaking/app/src/main/res/layout/activity_sign_up.xml
  Breaking/app/src/main/res/values/strings.xml
Labels: :bug: Bug, :ambulance: Hot-Fix

#40 style: implement User Page layout
  Breaking/app/src/main/java/com/dope/breaking/MainActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/fragment/LoadingFragment.kt
  Breaking/app/src/main/java/com/dope/breaking/fragment/NaviChartFragment.kt
  Breaking/app/src/main/java/com/dope/breaking/fragment/NaviChatFragment.kt
  Breaking/app/src/main/java/com/dope/breaking/fragment/NaviHomeFragment.kt
  Breaking/app/src/main/java/com/dope/breaking/fragment/NaviMissionFragment.kt
  Breaking/app/src/main/java/com/dope/breaking/fragment/NaviUserFragment.kt
  Breaking/app/src/main/java/com/dope/breaking/model/response/ResponseExistLogin.kt
  Breaking/app/src/main/java/com/dope/breaking/model/response/User.kt
  Breaking/app/src/main/java/com/dope/breaking/retrofit/RetrofitService.kt
  Breaking/app/src/main/res/drawable/feed_category_button_background.xml
  Breaking/app/src/main/res/drawable/ic_baseline_add_shopping_cart_24.xml
  Breaking/app/src/main/res/drawable/ic_baseline_bookmark_border_24.xml
  Breaking/app/src/main/res/drawable/ic_baseline_create_24.xml
  Breaking/app/src/main/res/drawable/ic_baseline_settings_24.xml
  Breaking/app/src/main/res/drawable/ic_breaking_logo2.xml
  Breaking/app/src/main/res/drawable/my_profile_edit_profile_btn_background.xml
  Breaking/app/src/main/res/layout/activity_main.xml
  Breaking/app/src/main/res/layout/fragment_loading.xml
  Breaking/app/src/main/res/layout/fragment_navi_chart.xml
  Breaking/app/src/main/res/layout/fragment_navi_chat.xml
  Breaking/app/src/main/res/layout/fragment_navi_home.xml
  Breaking/app/src/main/res/layout/fragment_navi_mission.xml
  Breaking/app/src/main/res/layout/fragment_navi_user.xml
  Breaking/app/src/main/res/layout/general_toolbar_layout.xml
  Breaking/app/src/main/res/menu/general_title_menu.xml
  Breaking/app/src/main/res/menu/title_menu.xml
  Breaking/app/src/main/res/values/colors.xml
  Breaking/app/src/main/res/values/strings.xml
Labels: :sparkles: Function, :busts_in_silhouette: Conversation, ✒Style

#43 style: separate layout of each post list into slide page
  Breaking/app/src/main/java/com/dope/breaking/adapter/UserViewPagerAdapter.kt
  Breaking/app/src/main/java/com/dope/breaking/fragment/NaviUserFragment.kt
  Breaking/app/src/main/java/com/dope/breaking/fragment/user_tab/BookmarkedTabFragment.kt
  Breaking/app/src/main/java/com/dope/breaking/fragment/user_tab/PostTabFragment.kt
  Breaking/app/src/main/java/com/dope/breaking/fragment/user_tab/PurchasedTabFragment.kt
  Breaking/app/src/main/res/drawable/ic_baseline_add_shopping_cart_24.xml
  Breaking/app/src/main/res/drawable/ic_baseline_bookmark_border_24.xml
  Breaking/app/src/main/res/drawable/ic_baseline_create_24.xml
  Breaking/app/src/main/res/layout/fragment_bookmarked_tab.xml
  Breaking/app/src/main/res/layout/fragment_loading.xml
  Breaking/app/src/main/res/layout/fragment_navi_user.xml
  Breaking/app/src/main/res/layout/fragment_post_tab.xml
  Breaking/app/src/main/res/layout/fragment_purchased_tab.xml
Labels: ✒Style

#44 style: implement Post Page Layout
  Breaking/app/src/main/AndroidManifest.xml
  Breaking/app/src/main/java/com/dope/breaking/board/PostActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/fragment/NaviHomeFragment.kt
  Breaking/app/src/main/java/com/dope/breaking/retrofit/RetrofitService.kt
  Breaking/app/src/main/res/drawable/btn_post_round.xml
  Breaking/app/src/main/res/drawable/ic_baseline_arrow_back_24.xml
  Breaking/app/src/main/res/drawable/ic_baseline_camera_alt_24.xml
  Breaking/app/src/main/res/drawable/ic_baseline_location_on_24.xml
  Breaking/app/src/main/res/drawable/post_input_background.xml
  Breaking/app/src/main/res/drawable/post_input_content_background.xml
  Breaking/app/src/main/res/layout/activity_post.xml
  Breaking/app/src/main/res/layout/fragment_navi_home.xml
  Breaking/app/src/main/res/values-night/themes.xml
  Breaking/app/src/main/res/values/colors.xml
  Breaking/app/src/main/res/values/strings.xml
  Breaking/app/src/main/res/values/themes.xml
Labels: ✒Style

#47 feat: implement edit profile in user profile page
  Breaking/app/src/main/AndroidManifest.xml
  Breaking/app/src/main/java/com/dope/breaking/EditProfileActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/ImageExpansionActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/MainActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/SignInActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/SignUpActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/SplashActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/fragment/LoadingFragment.kt
  Breaking/app/src/main/java/com/dope/breaking/fragment/NaviUserFragment.kt
  Breaking/app/src/main/java/com/dope/breaking/model/request/RequestUpdateUser.kt
  Breaking/app/src/main/java/com/dope/breaking/model/response/DetailUser.kt
  Breaking/app/src/main/java/com/dope/breaking/oauth/GoogleLogin.kt
  Breaking/app/src/main/java/com/dope/breaking/retrofit/RetrofitService.kt
  Breaking/app/src/main/java/com/dope/breaking/signup/Account.kt
  Breaking/app/src/main/java/com/dope/breaking/signup/Validation.kt
  Breaking/app/src/main/java/com/dope/breaking/util/DialogUtil.kt
  Breaking/app/src/main/java/com/dope/breaking/util/JwtTokenUtil.kt
  Breaking/app/src/main/java/com/dope/breaking/util/ValueUtil.kt
  Breaking/app/src/main/res/drawable/ic_baseline_arrow_back_black_24.xml
  Breaking/app/src/main/res/drawable/ic_baseline_arrow_back_white_24.xml
  Breaking/app/src/main/res/layout/activity_image_expansion.xml
  Breaking/app/src/main/res/layout/activity_sign_up.xml
  Breaking/app/src/main/res/layout/custom_dialog_multiple_button.xml
  Breaking/app/src/main/res/layout/fragment_navi_user.xml
  Breaking/app/src/main/res/values/strings.xml
Labels: :recycle: Refactoring, :sparkles: Function, ✒Style

#51 feat: implement following & follower list page
  Breaking/app/src/main/AndroidManifest.xml
  Breaking/app/src/main/java/com/dope/breaking/EditProfileActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/FollowActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/SignInActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/SignUpActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/SplashActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/UserPageActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/adapter/FollowAdapter.kt
  Breaking/app/src/main/java/com/dope/breaking/follow/Follow.kt
  Breaking/app/src/main/java/com/dope/breaking/fragment/NaviUserFragment.kt
  Breaking/app/src/main/java/com/dope/breaking/model/FollowData.kt
  Breaking/app/src/main/java/com/dope/breaking/oauth/GoogleLogin.kt
  Breaking/app/src/main/java/com/dope/breaking/retrofit/RetrofitService.kt
  Breaking/app/src/main/java/com/dope/breaking/util/JwtTokenUtil.kt
  Breaking/app/src/main/java/com/dope/breaking/util/ValueUtil.kt
  Breaking/app/src/main/res/layout/activity_follow.xml
  Breaking/app/src/main/res/layout/empty_layout_for_no_item.xml
  Breaking/app/src/main/res/layout/fragment_navi_user.xml
  Breaking/app/src/main/res/layout/item_follow_list.xml
  Breaking/app/src/main/res/values/colors.xml
  Breaking/app/src/main/res/values/strings.xml
Labels: :sparkles: Function, ✒Style

#53 fix: implement dynamic user page
  Breaking/app/src/main/java/com/dope/breaking/FollowActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/UserPageActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/adapter/FollowAdapter.kt
  Breaking/app/src/main/java/com/dope/breaking/fragment/LoadingFragment.kt
  Breaking/app/src/main/java/com/dope/breaking/fragment/NaviUserFragment.kt
  Breaking/app/src/main/java/com/dope/breaking/retrofit/RetrofitService.kt
  Breaking/app/src/main/java/com/dope/breaking/user/UserProfile.kt
  Breaking/app/src/main/res/drawable/feed_category_button_background.xml
  Breaking/app/src/main/res/drawable/sign_up_user_type_selected.xml
  Breaking/app/src/main/res/drawable/sign_up_user_type_unselected.xml
  Breaking/app/src/main/res/layout/fragment_navi_user.xml
Labels: :recycle: Refactoring, :sparkles: Function
