Repository Breaking-Dope/breaking-android, pull requests merged in 2022-08, with the labels that each got.

#54 feat: Implement Posting field processing
  Breaking/app/build.gradle
  Breaking/app/src/main/java/com/dope/breaking/board/MultiImageAdapter.kt
  Breaking/app/src/main/java/com/dope/breaking/board/PostActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/exception/ErrorFileSelectedException.kt
  Breaking/app/src/main/java/com/dope/breaking/model/PostData.kt
  Breaking/app/src/main/java/com/dope/breaking/model/PostLocation.kt
  Breaking/app/src/main/java/com/dope/breaking/post/Validation.kt
  Breaking/app/src/main/java/com/dope/breaking/signup/Validation.kt
  Breaking/app/src/main/java/com/dope/breaking/util/Utils.kt
  Breaking/app/src/main/java/com/dope/breaking/util/ValueUtil.kt
  Breaking/app/src/main/res/drawable/ic_baseline_cancel_24.xml
  Breaking/app/src/main/res/drawable/ic_default_post_image.xml
  Breaking/app/src/main/res/layout/activity_post.xml
  Breaking/app/src/main/res/layout/fragment_navi_home.xml
  Breaking/app/src/main/res/layout/multi_image_item.xml
  Breaking/app/src/main/res/values/colors.xml
Labels: :exclamation: Important, :sparkles: Function

#55 feat: implement follow & unfollow in user page
  Breaking/app/src/main/java/com/dope/breaking/FollowActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/UserPageActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/adapter/FollowAdapter.kt
  Breaking/app/src/main/java/com/dope/breaking/exception/UnLoginAccessException.kt
  Breaking/app/src/main/java/com/dope/breaking/follow/Follow.kt
  Breaking/app/src/main/java/com/dope/breaking/fragment/LoadingFragment.kt
  Breaking/app/src/main/java/com/dope/breaking/fragment/NaviUserFragment.kt
  Breaking/app/src/main/java/com/dope/breaking/model/response/User.kt
  Breaking/app/src/main/java/com/dope/breaking/retrofit/RetrofitService.kt
  Breaking/app/src/main/java/com/dope/breaking/user/UserProfile.kt
  Breaking/app/src/main/res/drawable/feed_category_button_background.xml
Labels: :recycle: Refactoring, :sparkles: Function, :busts_in_silhouette: Conversation

#58 hotfix: update user profile according to changed api
  Breaking/app/src/main/java/com/dope/breaking/EditProfileActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/model/request/RequestUpdateUser.kt
Labels: :ambulance: Hot-Fix, :recycle: Refactoring

#62 feat: implement follow & unfollow in following & follower list
  Breaking/app/src/main/java/com/dope/breaking/UserPageActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/adapter/FollowAdapter.kt
  Breaking/app/src/main/java/com/dope/breaking/fragment/NaviUserFragment.kt
  Breaking/app/src/main/java/com/dope/breaking/model/FollowData.kt
  Breaking/app/src/main/java/com/dope/breaking/model/response/User.kt
  Breaking/app/src/main/res/layout/fragment_navi_user.xml
  Breaking/app/src/main/res/layout/item_follow_list.xml
Labels: :recycle: Refactoring, :sparkles: Function

#65 feat: implement follow & unfollow in my follower list
  Breaking/app/src/main/java/com/dope/breaking/adapter/FollowAdapter.kt
Labels: :ambulance: Hot-Fix, :sparkles: Function

#66 feat: implement Posting Request to Server
  Breaking/app/build.gradle
  Breaking/app/src/main/java/com/dope/breaking/EditProfileActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/SignUpActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/board/MultiImageAdapter.kt
  Breaking/app/src/main/java/com/dope/breaking/board/PostActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/model/PostData.kt
  Breaking/app/src/main/java/com/dope/breaking/model/PostLocation.kt
  Breaking/app/src/main/java/com/dope/breaking/model/request/RequestPostData.kt
  Breaking/app/src/main/java/com/dope/breaking/model/response/ResponsePostUpload.kt
  Breaking/app/src/main/java/com/dope/breaking/post/PostManager.kt
  Breaking/app/src/main/java/com/dope/breaking/post/ValidationPost.kt
  Breaking/app/src/main/java/com/dope/breaking/retrofit/RetrofitService.kt
  Breaking/app/src/main/java/com/dope/breaking/signup/ValidationSignUp.kt
  Breaking/app/src/main/java/com/dope/breaking/util/Utils.kt
  Breaking/app/src/main/res/layout/activity_post.xml
  Breaking/app/src/main/res/values/colors.xml
Labels: :sparkles: Function

#67 style: implement layout of item of post list
  Breaking/app/src/main/java/com/dope/breaking/UserPageActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/adapter/UserPostAdapter.kt
  Breaking/app/src/main/java/com/dope/breaking/fragment/NaviChatFragment.kt
  Breaking/app/src/main/java/com/dope/breaking/fragment/NaviUserFragment.kt
  Breaking/app/src/main/java/com/dope/breaking/fragment/user_tab/PostTabFragment.kt
  Breaking/app/src/main/java/com/dope/breaking/model/response/User.kt
  Breaking/app/src/main/res/drawable/chip_post_exclusive_background.xml
  Breaking/app/src/main/res/drawable/chip_post_sold_background.xml
  Breaking/app/src/main/res/drawable/ic_baseline_bookmark_border_24.xml
  Breaking/app/src/main/res/drawable/ic_baseline_more_horiz_24.xml
  Breaking/app/src/main/res/drawable/ic_baseline_thumb_up_alt_24.xml
  Breaking/app/src/main/res/drawable/ic_default_post_image_size_up.xml
  Breaking/app/src/main/res/layout/activity_main.xml
  Breaking/app/src/main/res/layout/fragment_navi_chat.xml
  Breaking/app/src/main/res/layout/fragment_navi_home.xml
  Breaking/app/src/main/res/layout/fragment_post_tab.xml
  Breaking/app/src/main/res/layout/item_post_list.xml
  Breaking/app/src/main/res/values/colors.xml
Labels: :busts_in_silhouette: Conversation, ✒Style

#69 feat: implement main home layout with feed
  Breaking/app/src/main/AndroidManifest.xml
  Breaking/app/src/main/java/com/dope/breaking/adapter/FollowAdapter.kt
  Breaking/app/src/main/java/com/dope/breaking/adapter/UserPostAdapter.kt
  Breaking/app/src/main/java/com/dope/breaking/board/PostActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/fragment/NaviChatFragment.kt
  Breaking/app/src/main/java/com/dope/breaking/fragment/NaviHomeFragment.kt
  Breaking/app/src/main/java/com/dope/breaking/fragment/user_tab/PostTabFragment.kt
  Breaking/app/src/main/java/com/dope/breaking/model/PostLocation.kt
  Breaking/app/src/main/java/com/dope/breaking/model/request/RequestPostData.kt
  Breaking/app/src/main/java/com/dope/breaking/model/response/ResponseMainFeed.kt
  Breaking/app/src/main/java/com/dope/breaking/retrofit/RetrofitService.kt
  Breaking/app/src/main/java/com/dope/breaking/util/DateUtil.kt
  Breaking/app/src/main/res/drawable/chip_post_unsold_background.xml
  Breaking/app/src/main/res/drawable/hashtag_item_background.xml
  Breaking/app/src/main/res/drawable/ic_baseline_add_24.xml
  Breaking/app/src/main/res/drawable/ic_baseline_filter_list_24.xml
  Breaking/app/src/main/res/drawable/ic_baseline_search_24.xml
  Breaking/app/src/main/res/drawable/ic_baseline_sort_24.xml
  Breaking/app/src/main/res/drawable/ic_baseline_thumb_up_alt_24.xml
  Breaking/app/src/main/res/drawable/ic_baseline_tune_24.xml
  Breaking/app/src/main/res/drawable/main_button_background.xml
  Breaking/app/src/main/res/drawable/main_search_background.xml
  Breaking/app/src/main/res/layout/activity_follow.xml
  Breaking/app/src/main/res/layout/fragment_navi_home.xml
  Breaking/app/src/main/res/layout/item_hashtag_list.xml
  Breaking/app/src/main/res/layout/item_post_list.xml
  Breaking/app/src/main/res/layout/progress_dialog_layout.xml
  Breaking/app/src/main/res/values/colors.xml
  Breaking/app/src/main/res/values/strings.xml
Labels: :sparkles: Function, ✒Style

#71 feat: Implement location component using Map API when user posting
  Breaking/app/build.gradle
  Breaking/app/src/main/AndroidManifest.xml
  Breaking/app/src/main/java/com/dope/breaking/board/PostActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/exception/FailedGetLocationException.kt
  Breaking/app/src/main/java/com/dope/breaking/map/KakaoMapActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/map/MapListAdapter.kt
  Breaking/app/src/main/java/com/dope/breaking/model/LocationList.kt
  Breaking/app/src/main/java/com/dope/breaking/model/response/ResponseLocationSearch.kt
  Breaking/app/src/main/java/com/dope/breaking/retrofit/RetrofitManager.kt
  Breaking/app/src/main/java/com/dope/breaking/retrofit/RetrofitService.kt
  Breaking/app/src/main/java/com/dope/breaking/util/Utils.kt
  Breaking/app/src/main/res/drawable/ic_baseline_check_24.xml
  Breaking/app/src/main/res/drawable/ic_baseline_chevron_left_24.xml
  Breaking/app/src/main/res/drawable/ic_baseline_chevron_right_24.xml
  Breaking/app/src/main/res/drawable/ic_baseline_my_location_24.xml
  Breaking/app/src/main/res/drawable/location_list_btn_background.xml
  Breaking/app/src/main/res/layout/activity_kakao_map.xml
  Breaking/app/src/main/res/layout/activity_post.xml
  Breaking/app/src/main/res/layout/item_location_list.xml
  Breaking/app/src/main/res/values/colors.xml
  Breaking/app/src/main/res/values/strings.xml
Labels: :sparkles: Function

#75 feat: implement getting main feed including filter & sort
  Breaking/app/libs/libDaumMapAndroid.jar
  Breaking/app/src/main/java/com/dope/breaking/adapter/FeedAdapter.kt
  Breaking/app/src/main/java/com/dope/breaking/fragment/NaviHomeFragment.kt
  Breaking/app/src/main/java/com/dope/breaking/post/PostManager.kt
  Breaking/app/src/main/java/com/dope/breaking/retrofit/RetrofitService.kt
  Breaking/app/src/main/java/com/dope/breaking/util/DialogUtil.kt
  Breaking/app/src/main/java/com/dope/breaking/util/ValueUtil.kt
  Breaking/app/src/main/jniLibs/arm64-v8a/libDaumMapEngineApi.so
  Breaking/app/src/main/jniLibs/armeabi-v7a/libDaumMapEngineApi.so
  Breaking/app/src/main/jniLibs/armeabi/libDaumMapEngineApi.so
  Breaking/app/src/main/res/drawable/button_disable_background.xml
  Breaking/app/src/main/res/drawable/disable_input_background.xml
  Breaking/app/src/main/res/drawable/enable_input_background.xml
  Breaking/app/src/main/res/drawable/ic_baseline_calendar_month_24.xml
  Breaking/app/src/main/res/drawable/ic_baseline_clear_24.xml
  Breaking/app/src/main/res/drawable/ic_baseline_comment_24.xml
  Breaking/app/src/main/res/drawable/ic_baseline_thumb_up_alt_24.xml
  Breaking/app/src/main/res/drawable/theme_color_round_button.xml
  Breaking/app/src/main/res/layout/custom_dialog_filter_option.xml
  Breaking/app/src/main/res/layout/custom_dialog_sort_option.xml
  Breaking/app/src/main/res/layout/fragment_navi_home.xml
  Breaking/app/src/main/res/layout/item_loading.xml
  Breaking/app/src/main/res/layout/item_post_list.xml
  Breaking/app/src/main/res/values/strings.xml
Labels: :exclamation: Important, :sparkles: Function, ✒Style

#77 hotfix: implement expired jwt token handling with refresh token & access token
  Breaking/app/src/main/java/com/dope/breaking/EditProfileActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/FollowActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/SignInActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/SignUpActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/SplashActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/UserPageActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/adapter/FollowAdapter.kt
  Breaking/app/src/main/java/com/dope/breaking/board/PostActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/fragment/NaviHomeFragment.kt
  Breaking/app/src/main/java/com/dope/breaking/model/response/ResponseExistLogin.kt
  Breaking/app/src/main/java/com/dope/breaking/oauth/GoogleLogin.kt
  Breaking/app/src/main/java/com/dope/breaking/retrofit/RetrofitService.kt
  Breaking/app/src/main/java/com/dope/breaking/signup/Account.kt
  Breaking/app/src/main/java/com/dope/breaking/user/UserProfile.kt
  Breaking/app/src/main/java/com/dope/breaking/util/JwtTokenUtil.kt
  Breaking/app/src/main/java/com/dope/breaking/util/ValueUtil.kt
Labels: :ambulance: Hot-Fix, :lock: Security, :sparkles: Function

#78 feat: implement main feed detail part
  Breaking/app/src/main/java/com/dope/breaking/adapter/FeedAdapter.kt
  Breaking/app/src/main/java/com/dope/breaking/fragment/NaviHomeFragment.kt
  Breaking/app/src/main/java/com/dope/breaking/model/response/ResponseMainFeed.kt
  Breaking/app/src/main/java/com/dope/breaking/post/PostManager.kt
  Breaking/app/src/main/java/com/dope/breaking/retrofit/RetrofitService.kt
  Breaking/app/src/main/java/com/dope/breaking/util/NumberUtil.kt
  Breaking/app/src/main/res/drawable/ic_baseline_bookmark_border_theme_24.xml
  Breaking/app/src/main/res/drawable/ic_baseline_bookmark_theme_24.xml
  Breaking/app/src/main/res/drawable/ic_baseline_delete_24.xml
  Breaking/app/src/main/res/drawable/ic_baseline_edit_24.xml
  Breaking/app/src/main/res/drawable/ic_baseline_share_24.xml
  Breaking/app/src/main/res/drawable/none_background_click_background.xml
  Breaking/app/src/main/res/drawable/popup_menu_background.xml
  Breaking/app/src/main/res/layout/custom_main_feed_popup.xml
  Breaking/app/src/test/java/com/dope/breaking/NumberFormatTest.kt
Labels: :sparkles: Function, :test_tube: Test, ✒Style

#79 feat: Implement design post detail layout
  Breaking/app/src/main/AndroidManifest.xml
  Breaking/app/src/main/java/com/dope/breaking/adapter/FeedAdapter.kt
  Breaking/app/src/main/java/com/dope/breaking/board/PostActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/board/PostDetailActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/fragment/NaviHomeFragment.kt
  Breaking/app/src/main/java/com/dope/breaking/model/request/RequestPostData.kt
  Breaking/app/src/main/java/com/dope/breaking/model/response/ResponsePostDetail.kt
  Breaking/app/src/main/java/com/dope/breaking/retrofit/RetrofitService.kt
  Breaking/app/src/main/res/drawable/ic_post_comment.xml
  Breaking/app/src/main/res/drawable/ic_post_like.xml
  Breaking/app/src/main/res/layout/activity_post.xml
  Breaking/app/src/main/res/layout/activity_post_detail.xml
  Breaking/app/src/main/res/layout/item_comment_list.xml
  Breaking/app/src/main/res/layout/item_nested_comment_list.xml
  Breaking/app/src/main/res/values/strings.xml
Labels: :sparkles: Function, ✒Style

#80 fix: implement follow list as a pagination
  Breaking/app/src/main/java/com/dope/breaking/FollowActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/adapter/FeedAdapter.kt
  Breaking/app/src/main/java/com/dope/breaking/adapter/FollowAdapter.kt
  Breaking/app/src/main/java/com/dope/breaking/follow/Follow.kt
  Breaking/app/src/main/java/com/dope/breaking/model/FollowData.kt
  Breaking/app/src/main/java/com/dope/breaking/retrofit/RetrofitService.kt
  Breaking/app/src/main/java/com/dope/breaking/util/ValueUtil.kt
  Breaking/app/src/main/res/drawable/image_button_click_background.xml
  Breaking/app/src/main/res/layout/activity_follow.xml
  Breaking/app/src/main/res/layout/item_post_list.xml
Labels: :recycle: Refactoring, :sparkles: Function

#86 feat: implement logout
  Breaking/app/src/main/AndroidManifest.xml
  Breaking/app/src/main/java/com/dope/breaking/MainActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/NaviSettingActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/SettingActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/SignInActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/UserPageActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/fragment/NaviUserFragment.kt
  Breaking/app/src/main/java/com/dope/breaking/oauth/GoogleLogin.kt
  Breaking/app/src/main/java/com/dope/breaking/retrofit/RetrofitService.kt
  Breaking/app/src/main/java/com/dope/breaking/signup/Account.kt
  Breaking/app/src/main/res/drawable/text_click_background.xml
  Breaking/app/src/main/res/layout/activity_navi_setting.xml
  Breaking/app/src/main/res/layout/activity_setting.xml
Labels: :lock: Security, :sparkles: Function

#89 fix: add handling for empty list in main feed
  Breaking/app/src/main/java/com/dope/breaking/adapter/FeedAdapter.kt
  Breaking/app/src/main/java/com/dope/breaking/fragment/NaviHomeFragment.kt
  Breaking/app/src/main/java/com/dope/breaking/fragment/user_tab/BookmarkedTabFragment.kt
  Breaking/app/src/main/java/com/dope/breaking/fragment/user_tab/PostTabFragment.kt
  Breaking/app/src/main/java/com/dope/breaking/fragment/user_tab/PurchasedTabFragment.kt
Labels: :bug: Bug, :recycle: Refactoring

#90 feat : implement request post detail data
  Breaking/app/build.gradle
  Breaking/app/src/main/java/com/dope/breaking/board/ImageSliderAdapter.kt
  Breaking/app/src/main/java/com/dope/breaking/board/PostActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/board/PostDetailActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/model/response/ResponsePostDetail.kt
  Breaking/app/src/main/java/com/dope/breaking/model/response/ResponsePostWriter.kt
  Breaking/app/src/main/java/com/dope/breaking/post/PostManager.kt
  Breaking/app/src/main/java/com/dope/breaking/retrofit/RetrofitService.kt
  Breaking/app/src/main/java/com/dope/breaking/util/Utils.kt
  Breaking/app/src/main/res/drawable/bg_indicator_active.xml
  Breaking/app/src/main/res/drawable/bg_indicator_inactive.xml
  Breaking/app/src/main/res/drawable/ic_baseline_chat_24.xml
  Breaking/app/src/main/res/drawable/ic_baseline_do_not_disturb_24.xml
  Breaking/app/src/main/res/layout/activity_post_detail.xml
  Breaking/app/src/main/res/layout/custom_post_detail_content_popup.xml
  Breaking/app/src/main/res/layout/item_slider.xml
  Breaking/app/src/main/res/values/strings.xml
Labels: :sparkles: Function

#95 fix: modify logic error difference of date in feed
  Breaking/app/src/main/java/com/dope/breaking/util/DateUtil.kt
Labels: :bug: Bug

#96 refactor: modify to send null when no image in sign-up request
  Breaking/app/src/main/java/com/dope/breaking/EditProfileActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/SignUpActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/UserPageActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/adapter/FollowAdapter.kt
  Breaking/app/src/main/java/com/dope/breaking/fragment/NaviUserFragment.kt
  Breaking/app/src/main/java/com/dope/breaking/model/FollowData.kt
  Breaking/app/src/main/java/com/dope/breaking/model/response/DetailUser.kt
  Breaking/app/src/main/java/com/dope/breaking/model/response/ResponseExistLogin.kt
  Breaking/app/src/main/java/com/dope/breaking/model/response/ResponseJwtUserInfo.kt
  Breaking/app/src/main/java/com/dope/breaking/model/response/ResponseLogin.kt
  Breaking/app/src/main/java/com/dope/breaking/model/response/User.kt
  Breaking/app/src/main/java/com/dope/breaking/retrofit/RetrofitService.kt
  Breaking/app/src/main/java/com/dope/breaking/signup/Account.kt
Labels: :recycle: Refactoring

#98 hotfix: add condition for checking null
  Breaking/app/src/main/java/com/dope/breaking/model/response/ResponseExistLogin.kt
  Breaking/app/src/main/java/com/dope/breaking/model/response/ResponseLogin.kt
  Breaking/app/src/main/java/com/dope/breaking/model/response/User.kt
Labels: :bug: Bug, :ambulance: Hot-Fix

#100 feat: implement string, hashtag, user search function
  Breaking/app/src/main/AndroidManifest.xml
  Breaking/app/src/main/java/com/dope/breaking/FeedSearchActivity.kt
  Breaking/app/src/main/java/com/dope/breaking/adapter/UserSearchAdapter.kt
  Breaking/app/src/main/java/com/dope/breaking/fragment/NaviHomeFragment.kt
  Breaking/app/src/main/java/com/dope/breaking/model/response/ResponseUserSearch.kt
  Breaking/app/src/main/java/com/dope/breaking/post/PostManager.kt
  Breaking/app/src/main/java/com/dope/breaking/retrofit/RetrofitService.kt
  Breaking/app/src/main/java/com/dope/breaking/user/UserProfile.kt
  Breaking/app/src/main/res/drawable/hashtag_search_input_background.xml
  Breaking/app/src/main/res/drawable/input_background.xml
  Breaking/app/src/main/res/drawable/main_search_background.xml
  Breaking/app/src/main/res/drawable/user_search_input_background.xml
  Breaking/app/src/main/res/layout/activity_feed_search.xml
  Breaking/app/src/main/res/layout/fragment_navi_home.xml
  Breaking/app/src/main/res/layout/fragment_navi_user.xml
  Breaking/app/src/main/res/layout/item_post_list.xml
  Breaking/app/src/main/res/layout/item_user_search.xml
  Breaking/app/src/main/res/values/colors.xml
  Breaking/app/src/main/res/values/strings.xml
Labels: :sparkles: Function
